
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stvalkqotmltdiuavnaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0dmFsa3FvdG1sdGRpdWF2bmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzc0ODQsImV4cCI6MjA2MjcxMzQ4NH0.kB3Fue-zhojgVed1F2pNEUbx2YKAeIw3ZKd35e_eAYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Adding Database type as a global export so it can be used in the rest of the app
export type { Database };

// Define the tables that we have already created
export interface Tables {
  eb1a_forms: {
    id: string;
    data: any;
    status: 'draft' | 'submitted';
    created_at: string;
    updated_at: string;
    submitted_at?: string;
    user_id?: string | null;
  }
}
